name: PHP Tests

on:
  push:
  pull_request:

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, json
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Prepare app environment
        run: |
          cp -n .env.example .env || true
          php artisan key:generate --ansi
          php artisan optimize:clear

      - name: Ensure data exists for tests
        run: |
          mkdir -p data
          if [ -d tests/Fixtures/data ]; then
            cp -R tests/Fixtures/data/* data/ || true
          fi
          ls -la data || true

      - name: Run tests
        run: php artisan test --testdox
